# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Scene-Examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'AgoraSyncManager', '1.0.4'
  pod 'AgoraEditAvatar', :path => '../SDK/AgoraEditAvatar/AgoraEditAvatarLocal.podspec'
  pod 'AgoraRtcEngine_Special_iOS', '3.6.213'
  pod 'MBProgressHUD'
  pod 'Presentr'
end


