# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Scene-Examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  pod 'AgoraUIKit-iOS', '~> 1.0.0'
  pod 'AgoraSyncManager', :path => '../SDK/AgoraSyncManager/AgoraSyncManagerLocal.podspec'
  pod 'AgoraEditAvatar', :path => '../SDK/AgoraEditAvatar/AgoraEditAvatarLocal.podspec'
  pod 'MBProgressHUD'
  pod 'Presentr'
  pod 'AgoraRtcEngine_iOS', :path => '/Users/zyp/Agora/PodSpec/Avatar Cocos/AgoraRtcEngine_iOS.podspec'
end
